### ISSUE TITLE
Cannot Override Lockouts despite having QH Lockout Attempts.

### ISSUE THREAD

**Issue by a2aaron** [deifactor/wrtsc#28]
When I attempt to use Override Lockouts, the attempt always fails, even though I have done Kill Scout beforehand and have some QH Lockout Attempts. Is there some additional condition I need to meet to use Override Lockouts?

<img width="1053" alt="image" src="https://user-images.githubusercontent.com/15718048/206244727-8ab4566e-2ad0-40ad-ad8e-467f457bca04.png">

**Comment by deifactor** [comment]
You need to hijack the ship first. Adding a reason for the failure is something I should probably do (I'll open a separate issue for that if I ever pick this up again).
